enpoind relacionado con el front signuoForm PARA REGISTRAR USUARIO RE…
4GeeksAcademy/My_Game_Guru pull request #13
Opened 2024-08-09 19:21 UTC by adilsoN353

Changes were made to front folders in signupForm and in addition to that, create the link path with the enpoint in the operational Signup flux, users can now register in our database

2024-08-09 19:33 UTC, greyzeids approved these changes
ahora si

2024-08-09 19:55 UTC, Lichatti requested changes
check .gitignore and migrations/env.py
I have doubts about the Pipfile file

2024-08-09 19:55 UTC, Lichatti commented on migrations/env.py
folder migrations should not be updated

2024-08-09 19:55 UTC, Lichatti commented on .gitignore
this change has been added to another Pull Request

2024-08-11 07:39 UTC, adilsoN353 reviewed
carpetas eliminadas para realizar PR

2024-08-11 07:39 UTC, Lichatti approved these changes

2024-08-11 07:47 UTC, closed without merging